import { SubtitleItem } from './types';

export const SCENE_DURATION = 300; // 10 seconds at 30 fps

export const SUBTITLES: SubtitleItem[] = [
  {
    startFrame: 0,
    endFrame: 300,
    clipNumber: '01',
    tag: '痛点共鸣 · 决策瘫痪',
    title: '40分钟搜索疲劳与信息过载',
    voiceover: '周五晚上，你是不是也经历过这种崩溃：在小红书翻了 40 分钟攻略，收藏了一堆照骗，周末临近却依然定不下动线。',
    highlightText: '【40 分钟搜索疲劳】 照骗泛滥 · 缺乏履约',
  },
  {
    startFrame: 300,
    endFrame: 600,
    clipNumber: '02',
    tag: '矛盾升级 · 体验崩塌',
    title: '现场排队两小时与通用AI幻觉',
    voiceover: '好不容易挑中一家餐厅，现场排队两小时直接劝退；通用 AI 攻略全是废话，脱离物理世界，而且漏洞百出。',
    highlightText: '【通用 AI 物理悬空】 现场排号 1~2 小时',
  },
  {
    startFrame: 600,
    endFrame: 900,
    clipNumber: '03',
    tag: '破局登场 · 场景路由器',
    title: '美团本地生活出游 AI Agent 亮相',
    voiceover: '小红书负责造梦，而我们负责落地！美团生态首个本地生活出游 AI Agent——「周末去哪玩」，为你实现规划即履约。',
    highlightText: '「周末去哪玩」 规划即履约 · Planning is Execution',
  },
  {
    startFrame: 900,
    endFrame: 1200,
    clipNumber: '04',
    tag: '环境感知 · 数字孪生画像',
    title: '实时天气雷达与学信网身份',
    voiceover: 'Agent 毫秒级感知你的端侧画像与物理环境：周六有雨，自动过滤露天项目；打通学信网，直接激活学生特权底座。',
    highlightText: '🌧️ 实时降雨感知 (16℃) → 室内避雨 | 🎓 学信网实名蓝标',
  },
  {
    startFrame: 1200,
    endFrame: 1500,
    clipNumber: '05',
    tag: '交互亮点 · 人数阶梯杠杆',
    title: '自然语言输入与同行人数阶梯滑动条',
    voiceover: '不仅支持自然语言微调，更有独创的同行人数杠杆：滑动至 4 人寝室开黑，专车门票与团购动态分摊，人均立省 60%！',
    highlightText: '👥 同行人数：1人 → 4人 | 【人均立省 60% 越拼越省】',
  },
  {
    startFrame: 1500,
    endFrame: 1800,
    clipNumber: '06',
    tag: 'Generative UI · 履约画布',
    title: '动态生成式时空动线时间轴',
    voiceover: '告别传统 AI 冰冷的纯文本回复，动态出游画布秒级呈现：时空动线精准编排，时间、费用与状态一目了然。',
    highlightText: '【Generative UI 动态生成式画布】 时空动线自动求解',
  },
  {
    startFrame: 1800,
    endFrame: 2100,
    clipNumber: '07',
    tag: '数据底座 · 大众点评背书',
    title: '必玩榜认证与 NLP 差评避坑萃取',
    voiceover: '背靠大众点评 20 年真实数据，接入必玩榜与必吃榜。算法自动从真实差评中提炼避坑指南，彻底杜绝照骗翻车。',
    highlightText: '⭐ 大众点评必玩榜背书 | 【NLP 真实避坑短评萃取】',
  },
  {
    startFrame: 2100,
    endFrame: 2400,
    clipNumber: '08',
    tag: '极速交易 · 校园特权直签',
    title: '学信网免查验秒出电子学生票',
    voiceover: '免去线下排队与繁琐人工查验，学信网实名直连秒出电子学生票。现场直接扫码入闸，开启沉浸式畅玩。',
    highlightText: '🎟️ 学信网免验直连 | 【秒出电子码入闸 · 零换票】',
  },
  {
    startFrame: 2400,
    endFrame: 2700,
    clipNumber: '09',
    tag: '绝杀壁垒 · 动线哨兵',
    title: '离场前半小时结合动线自动代取号',
    voiceover: '这是我们的绝杀壁垒——动线排号哨兵！在你结束游玩前半小时，Agent 结合实时步行路程，自动替你远程取号。',
    highlightText: '⏰ 【动线排号哨兵】 离场前 30 分钟根据动线耗时自动代排',
  },
  {
    startFrame: 2700,
    endFrame: 3000,
    clipNumber: '10',
    tag: '履约奇迹 · 痛点清零',
    title: '到店 5 分钟叫号就座老字号大餐',
    voiceover: '走到店门口，刚好叫到你的号！直接入座享受热气腾腾的铜锅涮肉，把周末原本极度痛苦的排队等待，直接降为零！',
    highlightText: '现场排队 75 分钟 vs 到店 5 分钟叫号就座 | 【消灭排队摩擦】',
  },
  {
    startFrame: 3000,
    endFrame: 3300,
    clipNumber: '11',
    tag: '交通接驳 · 动线闭环',
    title: '单车雷达定位与 4 人特惠快车整车 AA',
    voiceover: '出行全链路无缝接驳：短途单车雷达实时定位，长途 4 人拼车整车 AA。比挤地铁更舒服，比单独打车省一半。',
    highlightText: '🚲 短途单车实时雷达 | 🚗 4人特惠车 AA · 比坐地铁更便宜',
  },
  {
    startFrame: 3300,
    endFrame: 3600,
    clipNumber: '12',
    tag: '资产回流 · 内容飞轮',
    title: '防伪数字足迹印章与点评笔记反哺',
    voiceover: '行程结束，一键生成带美团官方防伪的数字足迹手账，并无缝同步至大众点评，反哺社区真实内容飞轮。',
    highlightText: '📖 数字足迹防伪印章 | 【一键回流大众点评笔记 · 内容飞轮】',
  },
  {
    startFrame: 3600,
    endFrame: 3900,
    clipNumber: '13',
    tag: '商业合规 · 多 BU 飞轮',
    title: '微信群收款秒级清算与场景化交叉销售',
    voiceover: '基于微信群收款原路清算，合规无资金池沉淀；一次出游同时撬动门票、餐饮、出行四大业务线，实现场景化交叉销售。',
    highlightText: '💰 微信官方群收款 · 零资金池合规风险 | 🔄 多 BU 交叉销售',
  },
  {
    startFrame: 3900,
    endFrame: 4200,
    clipNumber: '14',
    tag: '终局定格 · 品牌升华',
    title: 'Next.js 14 × Taro 4 双端落地',
    voiceover: '以 Next.js 与 Taro 双端落地，用技术把决策做轻、把履约做实。让每一个年轻人的周末，都不再被辜负！',
    highlightText: '周末去哪玩 · Planning is Execution 规划即履约',
  },
];
