import { ItineraryPlan } from '@/types/poi';

export const mockItineraries: ItineraryPlan[] = [
  {
    id: 'BJ-798-HOT04',
    code: 'BJ-798-HOT04',
    title: '【避雨精选】798当代插画展 & 聚宝源铜锅涮肉',
    subtitle: '大众点评2026北京必玩榜 TOP 3 · 聚宝源必吃榜老字号',
    theme: '艺术看展 · 暖冬铜锅 · 避雨精选',
    coverImage:
      'https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=800&auto=format&fit=crop&q=80',
    tags: ['室内避雨', '大众点评必玩榜', '聚宝源必吃榜', '4人立省60%'],
    isRainFriendly: true,
    category: 'art',
    baseBudgetSolo: 95,
    budgetDual: 68,
    budgetQuad: 39.5,
    totalDurationHours: 6.5,
    originLocation: '北航学院路校区南门',
    address: '朝阳区酒仙桥路4号798艺术中心B07',
    hotScore: 98,
    transitSummary: '🚲 单车1.8km + 🚇 地铁14号线 + 🚗 特惠快车返校',
    tipsRed: '周末下午15:00后主馆排队超30分钟，聚宝源晚高峰等位超1小时，务必依靠哨兵提前锁号。',
    tipsGreen: '凭学生证可在B口服务台免费领取展区限定明信片；2号馆采光最佳适合人像。',
    invitationSlogan: '听说这周末免费看展，别在宿舍睡大觉了，晚上一起去聚宝源吃铜锅涮肉，4人成团只要¥39.5！',
    highlightTip:
      '画廊二层光线偏暗，拍摄人像建议自备小型便携补光灯；周六 15:30 后为进店高峰，智能哨兵提前排号免排队。',
    nodes: [
      {
        id: 'node-1',
        timeSlot: '13:30',
        poiId: 'poi-bike-1',
        poiName: '美团单车 · 校园接驳',
        poiCategory: '交通接驳',
        durationMinutes: 15,
        actionType: 'transit',
        notes: '北航南门出发，骑行 1.8km 直达 15 号线地铁站',
        transitFromPrev: {
          mode: 'bike',
          distanceKm: 1.8,
          durationMins: 15,
          costPerPerson: 1.5,
        },
      },
      {
        id: 'node-2',
        timeSlot: '14:00',
        poiId: 'poi-798-art',
        poiName: '798 青年当代插画艺术展',
        poiCategory: '艺术展览',
        durationMinutes: 150,
        actionType: 'visit',
        notes: '沉浸式观展 2.5 小时，打卡青年插画市集，免排队学生电子票直入',
        voucherCode: 'MT-STU-798-883921',
      },
      {
        id: 'node-3',
        timeSlot: '17:15',
        poiId: 'poi-sentinel',
        poiName: '智能排号哨兵介入',
        poiCategory: 'AI哨兵调度',
        durationMinutes: 45,
        actionType: 'break',
        notes: '距离餐厅 600m，AI 哨兵依据当前等位速度自动远程锁号 A-38，承诺到店 5 分钟内入座',
      },
      {
        id: 'node-4',
        timeSlot: '18:00',
        poiId: 'poi-jubaoyuan',
        poiName: '聚宝源·传统铜锅涮肉 (望京店)',
        poiCategory: '美食就餐',
        durationMinutes: 90,
        actionType: 'dine',
        notes: '核销美团 4 人大学生团购餐，人均 ¥39.5 畅吃鲜切手切羊肉',
        voucherCode: 'DP-GROUP-JBY-441209',
      },
      {
        id: 'node-5',
        timeSlot: '19:45',
        poiId: 'poi-taxi-return',
        poiName: '美团打车 · 特惠拼车返校',
        poiCategory: '返校交通',
        durationMinutes: 25,
        actionType: 'transit',
        notes: '全程 12km 特惠快车直达北航宿舍区，4人 AA 每人仅需 ¥8.0',
        transitFromPrev: {
          mode: 'rideshare',
          distanceKm: 12.0,
          durationMins: 25,
          costPerPerson: 8.0,
          sharedTotalCost: 32.0,
        },
      },
    ],
  },
  {
    id: 'BJ-WDK-BUDGET02',
    code: 'BJ-WDK-BUDGET02',
    title: '【30元极简】五道口小众旧书市集与老北京铜锅/小吃',
    subtitle: '大学路文化淘书 · 骑行直达 · 高性价比穷游首选',
    theme: '小众市集 · 极简预算 · 骑行出游',
    coverImage:
      'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=80',
    tags: ['极简预算', '骑行友好', '文化市集', '人均¥28'],
    isRainFriendly: false,
    category: 'market',
    baseBudgetSolo: 48,
    budgetDual: 35,
    budgetQuad: 28,
    totalDurationHours: 4.5,
    originLocation: '北航学院路校区西门',
    address: '海淀区成府路28号五道口大学路文创街区',
    hotScore: 92,
    transitSummary: '🚲 林荫道慢骑 2.1km 直达',
    tipsRed: '市集内部分独立文创手作溢价较高，建议重在翻淘旧书与黑胶唱片。',
    tipsGreen: '持学生证可在大学路合作咖啡馆立享美式咖啡半价优惠。',
    invitationSlogan: '五道口这周末有复古市集，一起骑车去淘黑胶和旧书，人均20多块钱逛吃一下午！',
    highlightTip:
      '旧书市集 14:00 开市黑胶唱片最全，周边老字号小吃下午 17:00 翻台前到店不用等位。',
    nodes: [
      {
        id: 'node-w1',
        timeSlot: '14:00',
        poiId: 'poi-w-bike',
        poiName: '绿色骑行前往五道口',
        poiCategory: '交通骑行',
        durationMinutes: 15,
        actionType: 'transit',
        notes: '沿学院路林荫道骑行 2.1km',
      },
      {
        id: 'node-w2',
        timeSlot: '14:30',
        poiId: 'poi-w-market',
        poiName: '万圣书园与大学路旧书市集',
        poiCategory: '市集淘书',
        durationMinutes: 120,
        actionType: 'visit',
        notes: '淘古旧黑胶、摄影画册与小众独立刊物',
      },
      {
        id: 'node-w3',
        timeSlot: '17:00',
        poiId: 'poi-w-food',
        poiName: '五道口老北京炙子烤肉与小吃',
        poiCategory: '特色美食',
        durationMinutes: 75,
        actionType: 'dine',
        notes: '人均 ¥28 大快朵颐，美团学生专属立减',
      },
    ],
  },
  {
    id: 'BJ-XS-HIKE03',
    code: 'BJ-XS-HIKE03',
    title: '【轻户外吸氧】西山/香山秋季轻徒步 + 农家现烤虹鳟鱼',
    subtitle: '大众点评周边游上榜 · 纯氧森林氧吧 · 团队聚餐推荐',
    theme: '近郊轻徒步 · 户外吸氧 · 农家美食',
    coverImage:
      'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&auto=format&fit=crop&q=80',
    tags: ['轻户外', '森林吸氧', '虹鳟鱼大餐', '适宜晴天'],
    isRainFriendly: false,
    category: 'hike',
    baseBudgetSolo: 88,
    budgetDual: 65,
    budgetQuad: 45,
    totalDurationHours: 7.0,
    originLocation: '北航学院路校区北门',
    address: '海淀区闵清路西山国家森林公园东门',
    hotScore: 95,
    transitSummary: '🚗 4人特惠整车快车直达景区后山',
    tipsRed: '雨天山路石阶湿滑起大雾，如遇降雨系统会自动降权并提示改选室内路线。',
    tipsGreen: '下午3点半开始从东门缓坡上山，刚好在5点20分赶上鬼笑石俯瞰落日晚霞。',
    invitationSlogan: '天气太好了！周六下午西山轻徒步看落日晚霞，顺便吃现烤虹鳟鱼，4人拼车AA超划算！',
    highlightTip: '秋季香山红叶季周末西郊线客流大，推荐 09:30 拼特惠快车整车直达景区后山。',
    nodes: [
      {
        id: 'node-h1',
        timeSlot: '09:30',
        poiId: 'poi-h-taxi',
        poiName: '特惠快车直达香山后山',
        poiCategory: '团队包车',
        durationMinutes: 40,
        actionType: 'transit',
        notes: '4人特惠拼车直达碧云寺入口',
      },
      {
        id: 'node-h2',
        timeSlot: '10:30',
        poiId: 'poi-h-mountain',
        poiName: '香山后山纯氧轻徒步',
        poiCategory: '户外爬山',
        durationMinutes: 180,
        actionType: 'visit',
        notes: '避开主干道人流，沿静翠峡至香炉峰轻量徒步',
      },
      {
        id: 'node-h3',
        timeSlot: '14:00',
        poiId: 'poi-h-trout',
        poiName: '山下一品香农家现烤虹鳟鱼',
        poiCategory: '农家大餐',
        durationMinutes: 90,
        actionType: 'dine',
        notes: '大众点评海淀周边游必吃，美团4人烤鱼套餐现捞现烤',
      },
    ],
  },
  {
    id: 'BJ-DT-TALK04',
    code: 'BJ-DT-TALK04',
    title: '【雨天解压】地坛地库青年脱口秀与沉浸读剧会',
    subtitle: '雨天首推救星！大学生半价解压发笑专场 · 暖气充足',
    theme: '室内避雨 · 喜剧脱口秀 · 青年社交',
    coverImage:
      'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800&auto=format&fit=crop&q=80',
    tags: ['雨天首推', '大学生半价', '爆笑解压', '人均¥30'],
    isRainFriendly: true,
    category: 'indoor',
    baseBudgetSolo: 55,
    budgetDual: 38,
    budgetQuad: 30,
    totalDurationHours: 3.5,
    originLocation: '北航学院路校区南门',
    address: '东城区和平里西街79号糖果大厦B1',
    hotScore: 91,
    transitSummary: '🚇 地铁2号线安定门站直达',
    tipsRed: '场馆座位无固定号，按入场顺序选座，前排有被演员互动风险。',
    tipsGreen: '购票时备注“高校学子”，入场时赠送一张免费特调饮料券。',
    invitationSlogan: '外面要降温下雨，咱们去听脱口秀吧！三十块钱笑足两小时，排解这周的期中压力！',
    highlightTip: '演出前 20 分钟入场可挑选最佳视野中区坐席，凭学生票可免费领热饮。',
    nodes: [
      {
        id: 'node-t1',
        timeSlot: '14:30',
        poiId: 'poi-t-subway',
        poiName: '地铁接驳直达安定门',
        poiCategory: '地铁出行',
        durationMinutes: 30,
        actionType: 'transit',
        notes: '地铁 2 号线直达糖果大厦地库出口',
      },
      {
        id: 'node-t2',
        timeSlot: '15:00',
        poiId: 'poi-t-show',
        poiName: '青年沉浸式脱口秀爆笑专场',
        poiCategory: '文化演出',
        durationMinutes: 100,
        actionType: 'visit',
        notes: '学信网认证高校专属座席，包含互动问答环节',
        voucherCode: 'MT-TALK-STU-9921',
      },
    ],
  },
  {
    id: 'BJ-LMH-NIGHT05',
    code: 'BJ-LMH-NIGHT05',
    title: '【0元漫步】亮马河国际风情水岸 · 晚风野餐慢行',
    subtitle: '北京人的“塞纳河” · 0元打卡水岸夜景 · 氛围感出片',
    theme: '夜市烟火 · 晚风野餐 · 零元漫步',
    coverImage:
      'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=800&auto=format&fit=crop&q=80',
    tags: ['0元免费', '水岸晚风', '氛围感神图', '夜间探索'],
    isRainFriendly: false,
    category: 'night',
    baseBudgetSolo: 0,
    budgetDual: 0,
    budgetQuad: 0,
    totalDurationHours: 3.0,
    originLocation: '北航学院路校区东门',
    address: '朝阳区亮马河南路国际风情水岸步道',
    hotScore: 94,
    transitSummary: '🚇 地铁10号线亮马桥站出站步行200米',
    tipsRed: '河岸阶梯晚间气温低微风较大，务必多备一件防风外套。',
    tipsGreen: '自带野餐垫和寝室零食，在蓝港码头观景台拍照最具氛围感。',
    invitationSlogan: '今晚亮马河晚风正好！自带零食去河边野餐散步看夜景，0元享受超治愈周末！',
    highlightTip: '建议 18:30 到达正好赶上两岸灯光亮起，适合胶片人像与轻徒步。',
    nodes: [
      {
        id: 'node-n1',
        timeSlot: '18:30',
        poiId: 'poi-n-walk',
        poiName: '亮马河国际风情步道夜游',
        poiCategory: '夜游漫步',
        durationMinutes: 120,
        actionType: 'visit',
        notes: '沿河慢行至蓝色港湾露天码头',
      },
    ],
  },
];
