import { SquadItem } from '@/types/squad';

export const mockSquads: SquadItem[] = [
  {
    id: 'squad-089',
    squadNo: '#089',
    title: '798 艺术展 + 聚宝源铜锅涮肉',
    associatedPlanId: 'BJ-798-HOT04',
    theme: '当代看展 · 必吃铜锅',
    leader: {
      id: 'u_beihang_lin',
      name: '林同学 (发起人)',
      avatar:
        'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=128&q=80',
      role: 'leader',
      university: '北京航空航天大学',
      college: '软件学院',
      creditScore: 5.0,
      isXuexinVerified: true,
      joinedAt: '周五 18:20',
      isPaidAA: true,
    },
    capacity: 4,
    currentMembers: [
      {
        id: 'u_beihang_lin',
        name: '林同学 (队长)',
        avatar:
          'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=128&q=80',
        role: 'leader',
        university: '北京航空航天大学',
        college: '软件学院',
        creditScore: 5.0,
        isXuexinVerified: true,
        joinedAt: '周五 18:20',
        isPaidAA: true,
      },
      {
        id: 'u_beihang_wang',
        name: '王同学',
        avatar:
          'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=128&q=80',
        role: 'member',
        university: '北京航空航天大学',
        college: '自动化学院',
        creditScore: 5.0,
        isXuexinVerified: true,
        joinedAt: '周五 19:15',
        isPaidAA: true,
      },
    ],
    departureTime: '周六 13:30',
    departureDate: '2026-10-18',
    countdownHours: 14,
    campusZone: '北航学院路',
    budgetPerPerson: 39.5,
    savingPercent: 60,
    status: 'recruiting',
    wechatGroupQrUrl:
      'https://images.unsplash.com/photo-1605792657660-596af9009e82?auto=format&fit=crop&w=300&q=80',
    isQrUnlocked: false,
    slogan: '拒绝周末寝室躺平！周六下午798看展+铜锅涮肉，已有2人还差2人即刻锁票！',
    admissionRules: {
      requireXuexin: true,
      minCreditScore: 4.8,
      preferredGrade: '本科生优先',
    },
  },
  {
    id: 'squad-092',
    squadNo: '#092',
    title: '暴风雪山庄沉浸密室 (3缺1烧脑推理局)',
    associatedPlanId: 'BJ-798-HOT04',
    theme: '实景密室 · 硬核推理',
    leader: {
      id: 'u_bupt_zhang',
      name: '张同学',
      avatar:
        'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=128&q=80',
      role: 'leader',
      university: '北京邮电大学',
      college: '计算机学院',
      creditScore: 4.9,
      isXuexinVerified: true,
      joinedAt: '周五 20:00',
    },
    capacity: 4,
    currentMembers: [
      {
        id: 'u_bupt_zhang',
        name: '张同学 (队长)',
        avatar:
          'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=128&q=80',
        role: 'leader',
        university: '北京邮电大学',
        college: '计算机学院',
        creditScore: 4.9,
        isXuexinVerified: true,
        joinedAt: '周五 20:00',
      },
      {
        id: 'u_bupt_chen',
        name: '陈同学',
        avatar:
          'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=128&q=80',
        role: 'member',
        university: '北京邮电大学',
        college: '信息安全',
        creditScore: 5.0,
        isXuexinVerified: true,
        joinedAt: '周五 20:30',
      },
      {
        id: 'u_tsinghua_liu',
        name: '刘同学',
        avatar:
          'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=128&q=80',
        role: 'member',
        university: '清华大学',
        college: '交叉信息院',
        creditScore: 5.0,
        isXuexinVerified: true,
        joinedAt: '周五 21:10',
      },
    ],
    departureTime: '周六 14:00',
    departureDate: '2026-10-18',
    countdownHours: 15,
    campusZone: '北邮海淀',
    budgetPerPerson: 48.0,
    savingPercent: 45,
    status: 'recruiting',
    isQrUnlocked: false,
    slogan: '纯机械实景硬核推理本，三缺一就等你来解开真相，美团学生专享特惠场。',
    admissionRules: {
      requireXuexin: true,
      minCreditScore: 4.8,
    },
  },
  {
    id: 'squad-104',
    squadNo: '#104',
    title: '香山秋季轻徒步 + 现烤虹鳟鱼',
    associatedPlanId: 'BJ-XS-HIKE03',
    theme: '轻徒步 · 森林吸氧',
    leader: {
      id: 'u_buaa_li',
      name: '李同学',
      avatar:
        'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=128&q=80',
      role: 'leader',
      university: '北京航空航天大学',
      college: '机械工程',
      creditScore: 5.0,
      isXuexinVerified: true,
      joinedAt: '周四 15:00',
    },
    capacity: 4,
    currentMembers: [
      {
        id: 'u_buaa_li',
        name: '李同学 (队长)',
        avatar:
          'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=128&q=80',
        role: 'leader',
        university: '北京航空航天大学',
        college: '机械工程',
        creditScore: 5.0,
        isXuexinVerified: true,
        joinedAt: '周四 15:00',
      },
      {
        id: 'u_pku_zhao',
        name: '赵同学',
        avatar:
          'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=128&q=80',
        role: 'member',
        university: '北大医学部',
        college: '临床医学',
        creditScore: 4.9,
        isXuexinVerified: true,
        joinedAt: '周五 11:20',
      },
      {
        id: 'u_buaa_sun',
        name: '孙同学',
        avatar:
          'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=128&q=80',
        role: 'member',
        university: '北京航空航天大学',
        college: '物理学院',
        creditScore: 5.0,
        isXuexinVerified: true,
        joinedAt: '周五 16:45',
      },
    ],
    departureTime: '周日 09:30',
    departureDate: '2026-10-19',
    countdownHours: 34,
    campusZone: '北航学院路',
    budgetPerPerson: 45.0,
    savingPercent: 50,
    status: 'recruiting',
    isQrUnlocked: false,
    slogan: '周日大晴天去香山后山吸氧避开人流，爬完直接山下一品香现烤虹鳟鱼AA！',
    admissionRules: {
      requireXuexin: true,
      minCreditScore: 4.5,
    },
  },
  {
    id: 'squad-058',
    squadNo: '#058',
    title: '万圣书园旧书市集 + 手冲漫谈',
    associatedPlanId: 'BJ-WDK-BUDGET02',
    theme: '旧书市集 · 手冲咖啡',
    leader: {
      id: 'u_thu_qiu',
      name: '邱同学',
      avatar:
        'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=128&q=80',
      role: 'leader',
      university: '清华大学',
      college: '人文学院',
      creditScore: 5.0,
      isXuexinVerified: true,
      joinedAt: '周三 19:00',
    },
    capacity: 2,
    currentMembers: [
      {
        id: 'u_thu_qiu',
        name: '邱同学 (队长)',
        avatar:
          'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=128&q=80',
        role: 'leader',
        university: '清华大学',
        college: '人文学院',
        creditScore: 5.0,
        isXuexinVerified: true,
        joinedAt: '周三 19:00',
      },
      {
        id: 'u_beihang_lin',
        name: '林同学',
        avatar:
          'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=128&q=80',
        role: 'member',
        university: '北京航空航天大学',
        college: '软件学院',
        creditScore: 5.0,
        isXuexinVerified: true,
        joinedAt: '周四 10:10',
      },
    ],
    departureTime: '已于上周末完成',
    departureDate: '2026-10-12',
    countdownHours: 0,
    campusZone: '清华东门',
    budgetPerPerson: 28.0,
    savingPercent: 35,
    status: 'completed',
    isQrUnlocked: true,
    slogan: '文艺淘书局，已完美履约完成。',
    admissionRules: {
      requireXuexin: true,
      minCreditScore: 4.8,
    },
  },
];
